// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cvToVs
std::vector<std::string> cvToVs(Rcpp::CharacterVector cv);
RcppExport SEXP icd9_cvToVs(SEXP cvSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type cv(cvSEXP );
        std::vector<std::string> __result = cvToVs(cv);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// icd9ComorbiditiesRaggedCpp
Rcpp::LogicalMatrix icd9ComorbiditiesRaggedCpp(Rcpp::CharacterVector vipCodes, Rcpp::CharacterVector icd9Short, Rcpp::List icd9Mapping);
RcppExport SEXP icd9_icd9ComorbiditiesRaggedCpp(SEXP vipCodesSEXP, SEXP icd9ShortSEXP, SEXP icd9MappingSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type vipCodes(vipCodesSEXP );
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type icd9Short(icd9ShortSEXP );
        Rcpp::traits::input_parameter< Rcpp::List >::type icd9Mapping(icd9MappingSEXP );
        Rcpp::LogicalMatrix __result = icd9ComorbiditiesRaggedCpp(vipCodes, icd9Short, icd9Mapping);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// icd9ComorbiditiesLongCpp
Rcpp::LogicalMatrix icd9ComorbiditiesLongCpp(Rcpp::CharacterVector visitId, Rcpp::CharacterVector icd9Short, Rcpp::List icd9Mapping);
RcppExport SEXP icd9_icd9ComorbiditiesLongCpp(SEXP visitIdSEXP, SEXP icd9ShortSEXP, SEXP icd9MappingSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type visitId(visitIdSEXP );
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type icd9Short(icd9ShortSEXP );
        Rcpp::traits::input_parameter< Rcpp::List >::type icd9Mapping(icd9MappingSEXP );
        Rcpp::LogicalMatrix __result = icd9ComorbiditiesLongCpp(visitId, icd9Short, icd9Mapping);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
