# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name cvToVs
#' @title convert CharacterVector to C++ vector of strings
#' @param cv vector of character strings
#' @return c++ vector of strings
#' @export
#' @import Rcpp
cvToVs <- function(cv) {
    .Call('icd9_cvToVs', PACKAGE = 'icd9', cv)
}

#' @name icd9MappingToVectorSetsCpp
#' @title icd9MappingToVectorSetsCpp
#' @description purpose is to index each comorbidity so we can quickly tell
#' whether a given ICD-9 code is in that set.
#' @param icd9Mapping
#' @return C++ vector of sets of characters
#' @export
#' @import Rcpp
icd9MappingToVectorSetsCpp <- function(icd9Mapping) {
    .Call('icd9_icd9MappingToVectorSetsCpp', PACKAGE = 'icd9', icd9Mapping)
}

#' @name icd9ComorbiditiesRaggedCpp
#' @title allocate co-morbidities based on list of vectors of ICD-9 codes
#' @param vipCodes list named by an Id (e.g. visit or patient), each with a character vector of short-form ICD-9 codes
#' @param icd9Mapping list named by  co-morbidity, with each item containing a character vector of ICD-9 codes for that co-morbidity
#' @return matrix of comorbidities, with row names being the visit or patients identifiers, column names being the comorbidities, and binary values.
#' @export
#' @import Rcpp
icd9ComorbiditiesRaggedCpp <- function(vipCodes, icd9Short, icd9Mapping) {
    .Call('icd9_icd9ComorbiditiesRaggedCpp', PACKAGE = 'icd9', vipCodes, icd9Short, icd9Mapping)
}

#' @name icd9ComorbiditiesLongCpp
#' @title allocate co-morbidities based on vectors of IDs and ICD-9 codes
#' @param visitId character vector of visit or patient identifiers
#' @template icd9-short
#' @param icd9Mapping list named by  co-morbidity, with each item containing a character vector of ICD-9 codes for that co-morbidity
#' @return matrix of comorbidities, with row names being the visit or patients identifiers, column names being the comorbidities, and binary values.
#' @examples
#'  icd9ComorbiditiesLongCpp(c("pat1","pa2","three"), c("042","4011", "44179"), ahrqComorbid)
#' @export
#' @import Rcpp
icd9ComorbiditiesLongCpp <- function(visitId, icd9Short, icd9Mapping) {
    .Call('icd9_icd9ComorbiditiesLongCpp', PACKAGE = 'icd9', visitId, icd9Short, icd9Mapping)
}

